import type { Action, Proof, Target, Twist } from "./types";

/**
 * Every fragment is a self-contained phrase. Targets carry their own article so
 * they can drop into any `{t}` slot without Romanian gender agreement breaking
 * the sentence — that constraint is why the generator can multiply pools freely
 * instead of hand-writing quests.
 *
 * Hard rule for the whole file, at every stupidity level: legal, safe, and it
 * never makes a bystander the butt of the joke. Maximum prostie is aimed at the
 * player, not at the people around them.
 */

export const TARGETS: Target[] = [
  // — obiecte, oriunde —
  { text: "un felinar stradal", kind: "obiect", min: 0, max: 100 },
  { text: "o ușă mai veche decât tine", kind: "obiect", min: 0, max: 100 },
  { text: "o cutie poștală", kind: "obiect", min: 0, max: 100 },
  { text: "un balcon plin de flori", kind: "obiect", min: 0, max: 100 },
  { text: "o bancă din lemn", kind: "obiect", min: 0, max: 100 },
  { text: "un graffiti", kind: "obiect", min: 0, max: 100 },
  { text: "o placă memorială", kind: "obiect", min: 0, max: 70 },
  { text: "un ceas public", kind: "obiect", min: 0, max: 100 },
  { text: "o fântână", kind: "obiect", min: 0, max: 100 },
  { text: "o statuie", kind: "obiect", min: 0, max: 100 },
  { text: "un coș de gunoi", kind: "obiect", min: 20, max: 100 },
  { text: "o bicicletă parcată", kind: "obiect", min: 0, max: 100 },
  { text: "o vitrină ciudată", kind: "obiect", min: 10, max: 100 },
  { text: "un capac de canal", kind: "obiect", min: 25, max: 100 },
  { text: "o scară exterioară", kind: "obiect", min: 0, max: 100 },
  { text: "un mozaic", kind: "obiect", min: 0, max: 80 },
  { text: "un afiș rupt pe jumătate", kind: "obiect", min: 10, max: 100 },
  { text: "o oglindă", kind: "obiect", min: 15, max: 100 },
  { text: "un stâlp plin de stickere", kind: "obiect", min: 10, max: 100 },
  { text: "o antenă de satelit", kind: "obiect", min: 20, max: 100 },
  { text: "un burlan", kind: "obiect", min: 30, max: 100 },
  { text: "o mașină parcată strâmb", kind: "obiect", min: 20, max: 100 },
  { text: "un hidrant", kind: "obiect", min: 25, max: 100 },
  { text: "o umbrelă uitată", kind: "obiect", min: 20, max: 100 },
  { text: "un geam cu perdea trasă", kind: "obiect", min: 15, max: 90 },
  { text: "o piatră de pavaj mai deschisă la culoare", kind: "obiect", min: 0, max: 100 },
  { text: "un clopotniță văzută printre clădiri", kind: "obiect", min: 0, max: 60 },
  { text: "o plantă care crește dintr-un zid", kind: "obiect", min: 0, max: 100 },

  // — oameni —
  { text: "un chelner", kind: "persoana", min: 0, max: 100, scenes: ["mancare", "oras", "noapte"] },
  { text: "un vânzător ambulant", kind: "persoana", min: 0, max: 100, scenes: ["oras", "piata", "plaja"] },
  { text: "un alt turist", kind: "persoana", min: 0, max: 100 },
  { text: "un localnic care nu pare grăbit", kind: "persoana", min: 0, max: 100 },
  { text: "un muzician stradal", kind: "persoana", min: 0, max: 100, scenes: ["oras", "parc", "noapte"] },
  { text: "un casier", kind: "persoana", min: 0, max: 100, scenes: ["piata", "mancare", "oras", "muzeu"] },
  { text: "un ghid turistic", kind: "persoana", min: 0, max: 100, scenes: ["muzeu", "oras"] },
  { text: "un om care își plimbă câinele", kind: "persoana", min: 0, max: 100, scenes: ["parc", "oras", "plaja", "munte"] },
  { text: "un vânzător de suveniruri", kind: "persoana", min: 0, max: 100, scenes: ["oras", "piata", "muzeu", "plaja"] },
  { text: "un supraveghetor de sală", kind: "persoana", min: 0, max: 80, scenes: ["muzeu"] },
  { text: "un salvamar", kind: "persoana", min: 0, max: 80, scenes: ["plaja"] },
  { text: "un drumeț cu rucsac enorm", kind: "persoana", min: 0, max: 100, scenes: ["munte"] },
  { text: "un barman", kind: "persoana", min: 0, max: 100, scenes: ["noapte", "mancare"] },
  { text: "un șofer de autobuz în pauză", kind: "persoana", min: 10, max: 100, scenes: ["transport", "oras"] },
  { text: "un om care așteaptă pe peron", kind: "persoana", min: 0, max: 100, scenes: ["transport"] },

  // — locuri —
  { text: "o stradă fără indicator vizibil", kind: "loc", min: 0, max: 100, scenes: ["oras", "noapte"] },
  { text: "cel mai îngust pasaj din zonă", kind: "loc", min: 0, max: 100, scenes: ["oras", "noapte"] },
  { text: "o scară care pare că nu duce nicăieri", kind: "loc", min: 10, max: 100 },
  { text: "o curte interioară deschisă publicului", kind: "loc", min: 0, max: 100, scenes: ["oras", "muzeu"] },
  { text: "o terasă", kind: "loc", min: 0, max: 100, scenes: ["oras", "mancare", "noapte", "plaja"] },
  { text: "un peron", kind: "loc", min: 0, max: 100, scenes: ["transport"] },
  { text: "o intersecție aglomerată", kind: "loc", min: 0, max: 100, scenes: ["oras", "transport"] },
  { text: "cel mai liniștit colț pe care îl găsești", kind: "loc", min: 0, max: 100 },
  { text: "o sală în care nu e nimeni", kind: "loc", min: 0, max: 100, scenes: ["muzeu"] },
  { text: "o potecă laterală", kind: "loc", min: 0, max: 100, scenes: ["munte", "parc"] },
  { text: "o porțiune de plajă fără prosoape", kind: "loc", min: 0, max: 100, scenes: ["plaja"] },
  { text: "un raft cu lucruri pe care nu le înțelegi", kind: "loc", min: 0, max: 100, scenes: ["piata", "oras"] },
  { text: "o bancă din care se vede tot", kind: "loc", min: 0, max: 100, scenes: ["parc", "munte", "oras", "plaja"] },

  // — animale —
  { text: "un porumbel", kind: "animal", min: 0, max: 100, scenes: ["oras", "parc", "piata", "transport"] },
  { text: "o pisică de cartier", kind: "animal", min: 0, max: 100, scenes: ["oras", "parc", "noapte"] },
  { text: "un câine plimbat în lesă", kind: "animal", min: 0, max: 100 },
  { text: "un pescăruș", kind: "animal", min: 0, max: 100, scenes: ["plaja", "transport"] },
  { text: "o furnică deosebit de ambițioasă", kind: "animal", min: 40, max: 100, scenes: ["parc", "munte", "plaja"] },
  { text: "o veveriță", kind: "animal", min: 0, max: 100, scenes: ["parc", "munte"] },
  { text: "o vrabie fără frică de oameni", kind: "animal", min: 0, max: 100, scenes: ["oras", "parc", "mancare"] },

  // — mâncare —
  { text: "o prăjitură pe care nu o recunoști", kind: "mancare", min: 0, max: 100, scenes: ["mancare", "piata", "oras"] },
  { text: "o băutură cu nume imposibil de pronunțat", kind: "mancare", min: 0, max: 100, scenes: ["mancare", "noapte", "piata"] },
  { text: "un fruct local", kind: "mancare", min: 0, max: 100, scenes: ["piata", "mancare"] },
  { text: "cel mai ieftin lucru din meniu", kind: "mancare", min: 0, max: 100, scenes: ["mancare", "noapte"] },
  { text: "o gustare de la un chioșc", kind: "mancare", min: 0, max: 100, scenes: ["oras", "plaja", "transport", "piata"] },
  { text: "un fel de mâncare pe care nu îl poți traduce", kind: "mancare", min: 0, max: 100, scenes: ["mancare", "piata"] },
  { text: "o înghețată într-o aromă suspectă", kind: "mancare", min: 10, max: 100, scenes: ["oras", "plaja", "parc"] },

  // — semne și text —
  { text: "un indicator rutier", kind: "semn", min: 0, max: 100, scenes: ["oras", "transport", "munte"] },
  { text: "un meniu scris de mână", kind: "semn", min: 0, max: 100, scenes: ["mancare", "piata", "noapte"] },
  { text: "o plăcuță cu numele străzii", kind: "semn", min: 0, max: 100, scenes: ["oras", "noapte"] },
  { text: "un anunț lipit pe un stâlp", kind: "semn", min: 0, max: 100, scenes: ["oras", "piata", "transport"] },
  { text: "o hartă turistică", kind: "semn", min: 0, max: 100 },
  { text: "un orar de autobuz", kind: "semn", min: 0, max: 100, scenes: ["transport", "oras"] },
  { text: "un panou publicitar", kind: "semn", min: 0, max: 100, scenes: ["oras", "transport", "noapte"] },
  { text: "o etichetă de muzeu", kind: "semn", min: 0, max: 100, scenes: ["muzeu"] },
  { text: "un semn care interzice ceva ciudat", kind: "semn", min: 10, max: 100 },
  { text: "un panou cu prețuri", kind: "semn", min: 0, max: 100, scenes: ["piata", "mancare", "plaja"] },
  { text: "un marcaj de traseu", kind: "semn", min: 0, max: 100, scenes: ["munte", "parc"] },
];

export const ACTIONS: Action[] = [
  // — 0-40: turism real, doar cu atenția dată la maxim —
  { text: "Găsește {t} și notează un detaliu pe care nu l-ai fi observat din mers.", accepts: ["obiect", "loc", "semn"], min: 0, max: 55 },
  { text: "Fotografiază {t} din trei unghiuri complet diferite.", accepts: ["obiect", "loc", "semn", "mancare"], min: 0, max: 60 },
  { text: "Stai două minute lângă {t} fără să faci nimic altceva.", accepts: ["obiect", "loc"], min: 0, max: 70 },
  { text: "Desenează {t} în treizeci de secunde, fără să ridici creionul.", accepts: ["obiect", "loc", "mancare", "animal"], min: 0, max: 100 },
  { text: "Găsește {t} și află povestea din spate de la cineva care lucrează prin zonă.", accepts: ["obiect", "loc"], min: 0, max: 50 },
  { text: "Numără câte lucruri de același fel ca {t} vezi pe o singură stradă.", accepts: ["obiect", "semn"], min: 0, max: 70 },
  { text: "Comandă {t} fără să întrebi ce conține.", accepts: ["mancare"], min: 0, max: 100, scenes: ["mancare", "piata", "noapte", "oras"] },
  { text: "Cere o recomandare de la {t} și urmeaz-o exact.", accepts: ["persoana"], min: 0, max: 60 },
  { text: "Ascultă un minut întreg lângă {t} și scrie toate sunetele pe care le auzi.", accepts: ["loc", "obiect"], min: 0, max: 60 },
  { text: "Descoperă {t} și caută cea mai veche dată scrisă pe suprafață.", accepts: ["obiect", "semn"], min: 0, max: 50 },
  { text: "Alege {t} și scrie o carte poștală imaginară despre ce vezi acolo.", accepts: ["obiect", "loc", "mancare"], min: 0, max: 65 },
  { text: "Găsește {t} și stabilește dacă merită sau nu o poză. Argumentează cu voce tare.", accepts: ["obiect", "loc", "semn"], min: 10, max: 80 },
  { text: "Mergi în linie dreaptă spre {t} fără să te uiți în telefon.", accepts: ["loc", "obiect"], min: 0, max: 70 },
  { text: "Întreabă {t} care e cel mai supraevaluat lucru din oraș.", accepts: ["persoana"], min: 10, max: 75 },
  { text: "Traduce {t} doar din context, fără dicționar și fără telefon.", accepts: ["semn"], min: 0, max: 70 },
  { text: "Găsește {t} și pune-i un nume propriu.", accepts: ["obiect", "animal", "loc"], min: 15, max: 100 },
  { text: "Fă o poză care să transforme {t} în atracția principală a orașului.", accepts: ["obiect", "semn", "mancare"], min: 10, max: 90 },
  { text: "Stai cu spatele la {t} și descrie din memorie, cu voce tare, tot ce tocmai ai văzut.", accepts: ["obiect", "loc", "semn"], min: 20, max: 100 },
  { text: "Găsește {t} și mai găsește încă două lucruri exact de aceeași culoare.", accepts: ["obiect", "semn", "mancare"], min: 0, max: 80 },
  { text: "Bea sau mănâncă {t} cât de încet poți suporta.", accepts: ["mancare"], min: 10, max: 100 },

  // — 30-70: începe să fie evident că faci ceva —
  { text: "Salută {t} politicos, cu o plecăciune scurtă.", accepts: ["obiect", "animal", "loc"], min: 30, max: 100 },
  { text: "Prezintă-te oficial, cu voce tare, lângă {t}. Nume complet, ocupație, planuri de viitor.", accepts: ["loc"], min: 40, max: 100 },
  { text: "Fă un tur ghidat de un minut despre {t}, pentru nimeni.", accepts: ["obiect", "loc", "semn"], min: 35, max: 100 },
  { text: "Aplaudă {t} timp de zece secunde.", accepts: ["obiect", "loc", "animal"], min: 45, max: 100 },
  { text: "Imită postura exactă în care se află {t}.", accepts: ["obiect", "animal"], min: 35, max: 100 },
  { text: "Explică pentru {t} cum funcționează internetul, în maximum trei propoziții.", accepts: ["animal", "obiect"], min: 50, max: 100 },
  { text: "Roagă {t} să te lase să treci, cu toată seriozitatea.", accepts: ["obiect"], min: 45, max: 100 },
  { text: "Fotografiază-te ținând {t} în palmă, prin trucul cu perspectiva.", accepts: ["obiect", "loc"], min: 30, max: 100 },
  { text: "Compune pe loc un cântec de patru versuri despre {t} și fredonează-l.", accepts: ["obiect", "loc", "mancare", "animal"], min: 40, max: 100 },
  { text: "Roagă {t} să îți recomande ceva ce nu se află în meniu sau în ghid.", accepts: ["persoana"], min: 25, max: 90 },
  { text: "Întreabă {t} dacă îți poate arăta cum se pronunță corect numele locului.", accepts: ["persoana"], min: 15, max: 85 },
  { text: "Mimează pentru {t} ce cauți, fără să spui niciun cuvânt.", accepts: ["persoana"], min: 45, max: 100 },
  { text: "Mergi cu pași uriași până ajungi la {t}.", accepts: ["obiect", "loc"], min: 40, max: 100 },
  { text: "Numără cu voce tare pașii până la {t} și anunță totalul ca pe un rezultat sportiv.", accepts: ["obiect", "loc"], min: 45, max: 100 },
  { text: "Adresează un compliment sincer, cu voce tare, către {t}.", accepts: ["obiect", "animal", "loc"], min: 40, max: 100 },
  { text: "Stai lângă {t} și prefă-te că aștepți pe cineva foarte important.", accepts: ["obiect", "loc"], min: 35, max: 100 },
  { text: "Găsește {t} și convinge un prieten că e cea mai faimoasă atracție din oraș.", accepts: ["obiect", "loc", "semn"], min: 40, max: 100 },
  { text: "Fă o recenzie de cinci stele, cu voce tare, pentru {t}.", accepts: ["obiect", "loc", "mancare"], min: 35, max: 100 },
  { text: "Fotografiază {t} ca și cum ai filma un documentar de investigație.", accepts: ["obiect", "animal", "semn"], min: 30, max: 100 },
  { text: "Cere sfaturi de viață de la {t}. Ascultă răspunsul cu toată atenția.", accepts: ["obiect", "animal"], min: 55, max: 100 },

  // — 60-100: prostie curată, dar tot legală și inofensivă —
  { text: "Ia-ți rămas bun de la {t} ca și cum ar fi o despărțire grea.", accepts: ["loc", "obiect", "animal"], min: 60, max: 100 },
  { text: "Fă zece pași ca un astronaut pe Lună până la {t}.", accepts: ["obiect", "loc"], min: 65, max: 100 },
  { text: "Prezintă {t} ca pe un membru al familiei tale, într-o poză de grup.", accepts: ["obiect", "animal", "loc"], min: 65, max: 100 },
  { text: "Ține un discurs de mulțumire de treizeci de secunde, cu fața către {t}.", accepts: ["loc"], min: 70, max: 100 },
  { text: "Fă un dans scurt de victorie când ajungi la {t}.", accepts: ["obiect", "loc"], min: 70, max: 100 },
  { text: "Roagă {t} să îți fie martor la o promisiune pe care o faci pe loc.", accepts: ["obiect", "animal"], min: 70, max: 100 },
  { text: "Comportă-te ca și cum {t} ar fi un secret de stat pe care îl protejezi.", accepts: ["obiect", "semn", "loc"], min: 70, max: 100 },
  { text: "Salută militar {t} ori de câte ori îți apare în față, timp de zece minute.", accepts: ["obiect", "semn"], min: 75, max: 100 },
  { text: "Fă cunoștință între doi prieteni și {t}, cu prezentări complete.", accepts: ["obiect", "animal"], min: 75, max: 100 },
  { text: "Șoptește un secret adevărat despre tine către {t}.", accepts: ["obiect", "animal", "loc"], min: 65, max: 100 },
  { text: "Mergi de-a lungul unei străzi întregi salutând tot ce seamănă cu {t}.", accepts: ["obiect", "semn"], min: 80, max: 100 },
  { text: "Fă o ședință foto profesionistă pentru {t}, cu tot cu indicații de regie.", accepts: ["obiect", "mancare", "animal"], min: 60, max: 100 },
  { text: "Explică-i unui prieten, cu date complet inventate, ce s-a întâmplat cândva la {t}.", accepts: ["loc"], min: 55, max: 100 },
  { text: "Mănâncă {t} cu cea mai serioasă expresie de critic culinar din lume.", accepts: ["mancare"], min: 55, max: 100 },
  { text: "Ridică-te și aplaudă în picioare când vezi prima dată {t}.", accepts: ["loc", "obiect"], min: 80, max: 100 },
  { text: "Cere permisiunea de a face o poză de la {t}. Așteaptă răspunsul.", accepts: ["obiect", "animal"], min: 70, max: 100 },
  { text: "Alege {t} și tratează drumul până acolo ca pe capătul unui pelerinaj. Fii emoționat.", accepts: ["obiect", "loc"], min: 75, max: 100 },
  { text: "Fă cinci minute de pauză lângă {t} și comentează totul ca un crainic sportiv.", accepts: ["loc", "obiect"], min: 75, max: 100 },
  { text: "Poartă-te ca și cum ai vedea {t} pentru prima dată în viață și te-ar impresiona profund.", accepts: ["obiect", "semn", "mancare"], min: 60, max: 100 },
  { text: "Roagă {t} să îți recomande ceva și apoi comandă exact opusul, politicos.", accepts: ["persoana"], min: 60, max: 100, scenes: ["mancare", "noapte", "piata"] },
  { text: "Întreabă {t} încotro e nordul și reacționează ca și cum ți-ar fi salvat viața.", accepts: ["persoana"], min: 65, max: 100 },
  { text: "Roagă {t} să îți spună un cuvânt în limba locului și folosește-l de zece ori în următoarea oră.", accepts: ["persoana"], min: 30, max: 100 },
];

export const TWISTS: Twist[] = [
  // — constrângeri blânde —
  { text: "Fă-o în mai puțin de trei minute.", cost: 2, min: 0, max: 100 },
  { text: "Fă-o fără să te uiți în telefon până termini.", cost: 3, min: 0, max: 100, blocks: ["telefon"] },
  { text: "Nu ai voie să te întorci pe unde ai venit.", cost: 3, min: 0, max: 100 },
  { text: "Fă-o cu ochii pe jumătate închiși.", cost: 3, min: 20, max: 100 },
  { text: "Nu ai voie să spui niciun cuvânt.", cost: 4, min: 10, max: 100, blocks: ["vorbire"] },
  { text: "Vorbește doar în șoaptă tot timpul.", cost: 4, min: 15, max: 100 },
  { text: "Fă-o ținând mâinile la spate.", cost: 4, min: 25, max: 100 },
  { text: "Fă-o fără să clipești mai mult decât e strict necesar.", cost: 3, min: 20, max: 100 },
  { text: "Nu ai voie să zâmbești.", cost: 4, min: 20, max: 100 },
  { text: "Nu ai voie să te oprești din mers.", cost: 4, min: 25, max: 100 },
  { text: "Fă-o cu un singur ochi acoperit.", cost: 4, min: 35, max: 100 },
  { text: "Fă-o folosind doar mâna nedominantă.", cost: 4, min: 25, max: 100 },
  { text: "Termină exact când se schimbă minutul pe ceas.", cost: 5, min: 20, max: 100 },
  { text: "Fă-o fără să pui piciorul pe nicio linie dintre pavele.", cost: 5, min: 30, max: 100 },
  { text: "Numără cu voce tare până la zece înainte să începi.", cost: 3, min: 30, max: 100, needs: ["vorbire"] },

  // — constrângeri care se văd —
  { text: "Fă-o mergând cu spatele ultimii zece pași.", cost: 6, min: 40, max: 100 },
  { text: "Fă-o în timp ce ții echilibrul pe un singur picior.", cost: 6, min: 45, max: 100 },
  { text: "Fă-o cu o voce mult mai gravă decât a ta.", cost: 6, min: 45, max: 100, needs: ["vorbire"] },
  { text: "Fă-o cu accentul cel mai prost pe care îl poți imita.", cost: 6, min: 50, max: 100, needs: ["vorbire"] },
  { text: "Fă-o folosind exclusiv gesturi largi de teatru.", cost: 6, min: 50, max: 100 },
  { text: "Fă-o ca și cum ai fi filmat pentru un reportaj serios.", cost: 5, min: 40, max: 100 },
  { text: "Fă-o în timp ce mergi în ritmul unei melodii pe care o fredonezi.", cost: 6, min: 50, max: 100, needs: ["vorbire"] },
  { text: "Începe fiecare propoziție cu „Sincer să fiu”.", cost: 5, min: 45, max: 100, needs: ["vorbire"] },
  { text: "Fă-o purtând ochelarii de soare, indiferent de oră.", cost: 4, min: 40, max: 100 },
  { text: "Fă-o cu rucsacul purtat în față.", cost: 5, min: 45, max: 100 },
  { text: "Fă-o ținând un obiect din buzunar ridicat ca pe o torță.", cost: 6, min: 55, max: 100 },
  { text: "Fă-o fără să atingi nimic cu mâinile.", cost: 6, min: 40, max: 100 },
  { text: "Fă-o din trei încercări, primele două intenționat greșite.", cost: 6, min: 50, max: 100 },
  { text: "Fă-o cât mai încet uman posibil.", cost: 5, min: 35, max: 100 },
  { text: "Fă-o de două ori, a doua oară exact la fel.", cost: 5, min: 40, max: 100 },

  // — prostie asumată —
  { text: "Fă-o mergând ca un astronaut.", cost: 8, min: 65, max: 100 },
  { text: "Prezintă-te ca inspector de porumbei, dacă te întreabă cineva ce faci.", cost: 9, min: 70, max: 100, needs: ["vorbire"] },
  { text: "Fă-o cu o pauză dramatică de cinci secunde la mijloc.", cost: 7, min: 60, max: 100 },
  { text: "Comentează tot ce faci la persoana a treia.", cost: 9, min: 65, max: 100, needs: ["vorbire"] },
  { text: "Fă-o ca și cum ar fi ultima ta zi pe planetă.", cost: 8, min: 65, max: 100 },
  { text: "Termină cu o plecăciune completă către trecători.", cost: 9, min: 70, max: 100, needs: ["vorbire"] },
  { text: "Fă-o în timp ce numeri cu voce tare, în ordine descrescătoare, de la douăzeci.", cost: 8, min: 65, max: 100, needs: ["vorbire"] },
  { text: "Anunță începutul misiunii cu voce tare, ca un crainic.", cost: 10, min: 75, max: 100, needs: ["vorbire"] },
  { text: "Fă-o mergând exclusiv în vârfuri.", cost: 8, min: 70, max: 100 },
  { text: "Fă-o cu o expresie de om profund emoționat.", cost: 8, min: 65, max: 100 },
  { text: "Fă-o și apoi mulțumește-le solemn celor din jur pentru răbdare.", cost: 10, min: 75, max: 100, needs: ["vorbire"] },
  { text: "Adaugă efecte sonore cu gura pentru fiecare mișcare.", cost: 10, min: 75, max: 100, needs: ["vorbire"] },
  { text: "Fă-o ca și cum ai explica totul unui public de milioane.", cost: 9, min: 70, max: 100, needs: ["vorbire"] },
  { text: "Fă-o purtându-te ca și cum ai fi în misiune secretă.", cost: 8, min: 60, max: 100 },
  { text: "Fă-o și încheie cu un „mulțumesc, a fost un vis” spus în gol.", cost: 10, min: 80, max: 100, needs: ["vorbire"] },
  { text: "Fă-o cu genunchii îndoiți, cu treizeci de centimetri mai scund.", cost: 9, min: 75, max: 100 },
  { text: "Fă-o în timp ce cari un prieten pe post de bagaj de mână imaginar.", cost: 9, min: 75, max: 100, blocks: ["prieten"] },
  { text: "Fă-o și cere pe loc feedback unui prieten, ca la o evaluare anuală.", cost: 9, min: 70, max: 100, blocks: ["prieten"], needs: ["vorbire"] },
  { text: "Fă-o de parcă ai fi urmărit de o dramă romantică.", cost: 8, min: 70, max: 100 },
  { text: "Fă-o cu brațele întinse ca un avion.", cost: 9, min: 75, max: 100 },
];

export const PROOFS: Proof[] = [
  { text: "un selfie cu subiectul în fundal", min: 0, max: 100 },
  { text: "o poză normală, fără filtre", min: 0, max: 60 },
  { text: "o poză intenționat foarte neclară", min: 30, max: 100 },
  { text: "un desen făcut pe un șervețel", min: 0, max: 100 },
  { text: "o notă vocală de zece secunde în care explici ce s-a întâmplat", min: 10, max: 100 },
  { text: "un video de cinci secunde", min: 15, max: 100 },
  { text: "o poză cu umbra ta și subiectul în același cadru", min: 20, max: 100 },
  { text: "un cuvânt nou notat în telefon", min: 0, max: 70 },
  { text: "bonul sau biletul, păstrat", min: 0, max: 80 },
  { text: "o poză cu pantofii tăi și subiectul", min: 25, max: 100 },
  { text: "trei cuvinte scrise de mână despre cum a fost", min: 0, max: 100 },
  { text: "o poză făcută fără să te uiți în ecran", min: 35, max: 100 },
  { text: "un martor ocular care confirmă", min: 40, max: 100 },
  { text: "o poză în care nu se înțelege absolut nimic", min: 55, max: 100 },
  { text: "un mesaj trimis unui prieten cu exact ce ai făcut", min: 30, max: 100 },
  { text: "o captură cu ora exactă la care ai terminat", min: 10, max: 100 },
  { text: "o poză de grup în care subiectul e vedeta", min: 45, max: 100 },
  { text: "un scurt raport oficial scris în telefon", min: 50, max: 100 },
  { text: "o poză înainte și una după", min: 0, max: 100 },
  { text: "un obiect mic, gratuit și legal, luat ca amintire", min: 20, max: 90 },
  { text: "o notă vocală în care îți dai singur nota de la 1 la 10", min: 45, max: 100 },
  { text: "cuvântul de onoare, spus cu mâna pe inimă", min: 60, max: 100 },
];

/** Numele misiunii — scurt, imprimabil pe un tricou. */
export const TITLES: Proof[] = [
  { text: "Recunoaștere de teren", min: 0, max: 35 },
  { text: "Detaliul pierdut", min: 0, max: 40 },
  { text: "Turistul atent", min: 0, max: 30 },
  { text: "Ochi de vultur", min: 0, max: 45 },
  { text: "Colecționarul", min: 0, max: 50 },
  { text: "Ruta lungă", min: 0, max: 45 },
  { text: "Nota de subsol", min: 0, max: 45 },
  { text: "Anchetă de cartier", min: 10, max: 60 },
  { text: "Documentarul", min: 15, max: 70 },
  { text: "Protocol de salut", min: 30, max: 80 },
  { text: "Contact vizual", min: 25, max: 75 },
  { text: "Misiune neoficială", min: 20, max: 70 },
  { text: "Operațiunea Firesc", min: 35, max: 85 },
  { text: "Ghidul inventat", min: 40, max: 90 },
  { text: "Ședința foto", min: 30, max: 85 },
  { text: "Criticul", min: 35, max: 85 },
  { text: "Diplomatul", min: 45, max: 95 },
  { text: "Discursul", min: 55, max: 100 },
  { text: "Inspectorul", min: 55, max: 100 },
  { text: "Ceremonia", min: 60, max: 100 },
  { text: "Spectacolul", min: 60, max: 100 },
  { text: "Demnitate zero", min: 75, max: 100 },
  { text: "Fără martori, sperăm", min: 75, max: 100 },
  { text: "Protocol de clovn", min: 80, max: 100 },
  { text: "Ultima ta zi de reputație", min: 85, max: 100 },
  { text: "Marea prostie", min: 80, max: 100 },
  { text: "Turneul de adio", min: 70, max: 100 },
  { text: "Momentul de glorie", min: 50, max: 100 },
];
